databases:
  - name: hello-rails
    databaseName: hello_rails
    user: mysite

services:
  - type: web
    name: hello-rails
    env: ruby
    buildCommand: "./bin/build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    # envVars:
    #   - key: DATABASE_URL
    #     fromDatabase:
    #       name: mysite
    #       property: connectionString
    #   - key: RAILS_MASTER_KEY
    #     sync: false
